name: Auto-Update Data (insider-2)

on:
  schedule:
    - cron: '0 2,14 * * *'
  workflow_dispatch:
  
jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the target repository
        uses: actions/checkout@v2
        with:
          repository: St-Pavlov-Foundation/re1999-data
          ref: insider-2
          token: ${{ secrets.UPDATE_TOKEN }} 
          path: re1999-data

      - name: Checkout the target repository
        uses: actions/checkout@v2
        with:
          repository: St-Pavlov-Foundation/re1999-depack
          token: ${{ secrets.DEPACK_TOKEN }} 
          path: re1999-depack
          submodules: true

      - name: Set up python 3.11
        uses: actions/setup-python@v4
        with:
            python-version: '3.11'

      - name: Generate unpacked data
        id: bin
        run: |
          cd re1999-depack
          pip install -r requirements.txt
          python main.py --server-type 2 --data-path ../re1999-data/data -u
          echo "version=`python main.py --data-path ../re1999-data/data --res-version`" >> "$GITHUB_OUTPUT"

      - name: Commit and push changes to the target repository
        if: steps.bin.outputs.version
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: St. Pavlov [bot]
          author_email: st.pavlov.bot@users.noreply.github.com
          message: "${{ steps.bin.outputs.version }}"
          cwd: "re1999-data"
